select S_INFO_WINDCODE as ticker,TRADE_DT as date,
 s_west_netprofit_ftm_chg_1m,
 s_west_netprofit_ftm_chg_3m ,
 s_west_netprofit_ftm_chg_6m ,
 s_west_eps_ftm_chg_1m ,
 s_west_eps_ftm_chg_3m ,
 s_west_eps_ftm_chg_6m ,
 S_WEST_SALES_FTM_CHG_1M ,
 s_west_sales_ftm_chg_3m ,
 s_west_sales_ftm_chg_6m ,
 s_west_netprofit_fy1_chg_1m ,
 s_west_netprofit_fy1_chg_3m ,
 s_west_netprofit_fy1_chg_6m,
 s_west_eps_fy1_chg_1m,
 s_west_eps_fy1_chg_3m ,
 s_west_eps_fy1_chg_6m ,
 S_WEST_SALES_FY1_CHG_1M,
 s_west_sales_fy1_chg_3m,
 s_west_sales_fy1_chg_6m,
 s_west_netprofit_ftm_1m,
 s_west_netprofit_ftm_3m,
 s_west_netprofit_ftm_6m ,
 s_west_eps_ftm_1m,
 s_west_eps_ftm_3m,
 s_west_eps_ftm_6m,
 s_west_sales_ftm_1m,
 s_west_sales_ftm_3m,
 s_west_sales_ftm_6m
 s_west_netprofit_fy1_1m,
 s_west_netprofit_fy1_3m,
 s_west_netprofit_fy1_6m,
 s_west_eps_fy1_1m,
 s_west_eps_fy1_3m,
 s_west_eps_fy1_6m,
 s_west_sales_fy1_1m,
 s_west_sales_fy1_3m,
 s_west_sales_fy1_6m ,
 s_west_eps_fygrowth,
 s_west_netprofitmaxmin_fy1,
 s_west_epsmaxmin_fy1,
 s_west_salesmaxmin_fy1,
 s_west_stdnetprofit_fy1,
 s_west_stdeps_fy1,
 s_west_stdsales_fy1 FROM wind.consensusexpectationfactor where TRADE_DT>='{0}' and TRADE_DT<='{1}'